### ISSUE TITLE
Can´t find the Integration 

### ISSUE THREAD

**Issue by bussio** [osks/hass-gardena-smart-system#2] opened 2020-05-23 12:54 UTC
I entered the integration under HACS as a custom repository. It then appears there under integration. After pressing Install, the files are also copied to custom_components / gardena_smart_system. In HACS, however, the integration remains there as a new repository. If I now go to Settings / Integrations, I don't find any integration gardena smart sytem that I can set up ?!

**Comment by osks** [comment] 2020-05-23 13:06
Did you restart Home Assistant after installing? If not, could you try that?

**Comment by bussio** [comment] 2020-05-23 13:34
Ok, after the 3rd restart it worked now. However, there are now problems entering the data. Are they somehow not recognized? The password is the Gardena Account password? 
After I have entered the required data, the input field appears again without data. Otherwise nothing happens?

**Comment by Jpsy** [comment] 2020-05-23 15:33
Hi @osks 
I can confirm that there is something going wrong in HACS. As @bussio said, the integration tile in HACS stays in the "Install" state, even after installing.
![image](https://user-images.githubusercontent.com/1806058/82734312-8720b680-9d1a-11ea-8849-73d070c8bb99.png)
"Install" clicked:
![image](https://user-images.githubusercontent.com/1806058/82734348-c4854400-9d1a-11ea-965e-7cf19c6fa9c4.png)
"Install" clicked in the second dialog and waited until installation has finished:
![image](https://user-images.githubusercontent.com/1806058/82734360-d6ff7d80-9d1a-11ea-8bee-a55753238301.png)
The subfolder structure is correctly created. 
I cannot verify the problem that the integration cannot be added into HA because I had it already installed, configured and loaded manually before I used HACS to install it again. For me it appears immediatelly when I click the Plus button in the HA integrations manager.

**Comment by bussio** [comment] 2020-05-23 16:05
@Jpsy, after I clicked the "Hide" button, the integration into HACS was taken over. Only then it does not work for me when entering the data, which I then enter in the integration.

**Comment by Jpsy** [comment] 2020-05-23 17:04
@bussio jepp, tried that and the hide button actually hides the buttons "Install", "Information", and "Hide". I have to say that IMHO the naming of that button is not very intuitive.
![image](https://user-images.githubusercontent.com/1806058/82736159-b984e080-9d27-11ea-8c7c-b54b0a6d75e7.png)
So bottomlines: 
1. The installation through HACS works - probably as expected. 
2. Unfortunately I cannot reproduce your problems with activating the integration in HA integration manager - could be because I had installed the component manually before I switched to HACS. Sorry.

**Comment by Jpsy** [comment] 2020-05-23 17:21
Ooookay... after a restart I discovered that my existing integration has gone "unavailable"! So the Hide button does probably more than just hiding the unwanted buttons. Which is what I would actually expect, because otherwise it would be named "Finish" or something like that. I have restarted HA several times before - even after switching to HACS. So this is definitely related to the Hide button. I will try to investigate further and report back.

**Comment by bussio** [comment] 2020-05-23 17:54
>  2. Unfortunately I cannot reproduce your problems with activating the integration in HA integration manager - could be because I had installed the component manually before I switched to HACS. Sorry.

Shame on me ... I didn't follow point 5 of the description "Click on" Connect new API "and connect the Authentication API and the GARDENA smart system API." After I did that, the input dialog also worked.

**Comment by bussio** [comment] 2020-05-23 17:57
> 2. Unfortunately I cannot reproduce your problems with activating the integration in HA integration manager - could be because I had installed the component manually before I switched to HACS. Sorry.

Shame on me ... I didn't follow point 5 of the description "Click on" Connect new API "and connect the Authentication API and the GARDENA smart system API." After I did that, the input dialog also worked.

From my side this issue can be closed.

**Comment by Jpsy** [comment] 2020-05-23 19:08
Don't close it so fast. After all my installation went completely havoc after hitting that HACS hide button. I managed to get the component back through a series of uninstalls and reinstalls with weird side effects like removing it from HACS than see it reappearing by itself after a reboot, adding the integration in HA and seeing it loop through the "Choose integration" dialog again and again, etc.
I now have it back. The only hint for the cause that I have might be the following log error that I captured when it all began, so just after using the Hide button in HACS. This log error kept reappearing after each reboot until I started to uninstall the integration and then the component.

![image](https://user-images.githubusercontent.com/1806058/82738653-864b4d00-9d39-11ea-969c-65f9fb9d702b.png)

I don't know if it is of any help to identify what went wrong.
I hope that somebody else who did a fresh install through HACS can comment here.

**Comment by osks** [comment] 2020-05-25 07:33
Which versions of HACS are you using? I have tested with 1.0 and 1.0.3. I think you must restart HASS after installing the integration (before trying to set it up).

**Comment by Jpsy** [comment] 2020-05-27 20:41
I have tested with 1.0.0 and (I think) 1.0.1. Updates of the 1.0 versions came in so quickly that I am not sure about the latter.
 
I always restart HA after component installations and uninstalls, just to make sure. So yes, I did restart.

**Comment by Jpsy** [comment] 2020-05-27 20:44
Let us close this issue and open a new one if this should happen again.

**Comment by osks** [comment] 2020-05-28 05:37
I agree, let's close it and open a new one if it happens again and we have something to troubleshoot.

**Closed as completed by osks** 2020-05-28 05:37 UTC
